FROM registry.sh.nextgenwaterprediction.com/infrastructure/rockylinux/rockylinux:latest

# Install runtime dependencies
RUN set -eux; \
    dnf install -y yum-utils; \
    dnf config-manager --set-enabled crb; \
    dnf install -y epel-release; \
    dnf install -y \
        file \
        findutils \
        jq \
        libpq \
        git \
        openssl openssl-devel \
        python3.11 python3.11-libs python3.11-devel \
        python3.11-pip \
        python3.11-setuptools \
        which; \
    dnf clean all

# Configure Git with the GitLab token using BuildKit secret mount
RUN --mount=type=secret,id=gitlab_token \
    set -eux; \
    git config --global url."https://oauth2:$(cat /run/secrets/gitlab_token)@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"

# Set up working directory
WORKDIR /ngencerf/ngencerf-server/

# Copy requirements and .git folder
COPY requirements.txt .

# Install Python virtual environment
ENV VIRTUAL_ENV=/ngencerf/ngencerf-python
RUN set -eux; \
    python3.11 -m venv ${VIRTUAL_ENV}
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

# Install dependencies
RUN set -eux; \
    pip3 install -r requirements.txt

ARG CREATE_INPUT_TAG
ARG RUN_SWE_TAG
RUN set -eux; \
    pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-cal.git@${CREATE_INPUT_TAG}#egg=createInput&subdirectory=python/createInput" ; \
    pip install -e "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-forcing.git@${RUN_SWE_TAG}#egg=swe_processing&subdirectory=swe_processing" ; \
    # Lock numpy and netcdf4 versions so t-route doesn't break
    pip3 install "numpy==1.26.4" "pandas~=2.2.2" ; \
    pip3 cache purge; \
    rm --force /root/.gitconfig

# Extract Git information and write it to the JSON file specified by $GIT_INFO_PATH
ENV GIT_INFO_PATH=git_info.json
# Should parallel similar functionality in the run_cerf.sh
COPY .git .git
RUN jq -n \
    --arg commit_hash "$(git rev-parse HEAD)" \
    --arg branch "$(git rev-parse --abbrev-ref HEAD)" \
    --arg tags "$(git tag --points-at HEAD | tr '\n' ' ')" \
    --arg author "$(git log -1 --pretty=format:'%an')" \
    --arg commit_date "$(date -u -d @$(git log -1 --pretty=format:'%ct') +'%Y-%m-%d %H:%M:%S UTC')" \
    --arg message "$(git log -1 --pretty=format:'%s' | tr '\n' ';')" \
    --arg build_date "$(date -u +'%Y-%m-%d %H:%M:%S UTC')" \
    '{"cerfServer": {commit_hash: $commit_hash, branch: $branch, tags: $tags, author: $author, commit_date: $commit_date, message: $message, build_date: $build_date}}' \
    > "$GIT_INFO_PATH"

# Copy application code
COPY . /ngencerf/ngencerf-server/

# Remove .git directory
RUN rm -rf .git

# Copy additional configuration files
COPY ./cerfserver-docker.env /ngencerf/ngencerf-server/cerfserver.env
COPY ./cerfServer/__.env-docker-prod /ngencerf/ngencerf-server/cerfServer/.env
COPY ./cerfServer/__local_settings_prod_pw.py /ngencerf/ngencerf-server/cerfServer/local_settings.py

# Set the entry point and expose the application port
ENTRYPOINT [ "/ngencerf/ngencerf-server/runCerf.sh" ]
EXPOSE 8000
