FROM registry.sh.nextgenwaterprediction.com/infrastructure/rockylinux/rockylinux:latest

# Install runtime dependencies
RUN set -eux && \
    dnf install -y yum-utils epel-release && \
    dnf config-manager --set-enabled crb && \
    dnf install -y \
        file \
        findutils \
        jq \
        libpq \
        git \
        openssl openssl-devel \
        python3.11 python3.11-libs python3.11-devel \
        python3.11-pip \
        python3.11-setuptools \
        singularity-ce \
        # The following needed for partitionGenerator
        make \
        cmake \
        gcc-c++ \
        sqlite-devel \
        udunits2 udunits2-devel \
        dnf-plugins-core && \
    dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo && \
    dnf install -y docker-ce-cli && \
    dnf clean all

# Install Boost 1.79.0 from source
ARG BOOST_VERSION=1.79.0
RUN --mount=type=cache,target=/root/.cache/cmake,id=cmake-boost \
    set -eux && \
    curl --location --output boost.tar.gz "https://archives.boost.io/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//./_}.tar.gz" && \
    mkdir -p /opt/boost && \
    tar --extract --directory /opt/boost --strip-components=1 --file boost.tar.gz && \
    rm boost.tar.gz

# Configure Git with the GitLab token using BuildKit secret mount
RUN --mount=type=secret,id=gitlab_token \
    set -eux && \
    git config --global url."https://oauth2:$(cat /run/secrets/gitlab_token)@gitlab.sh.nextgenwaterprediction.com/".insteadOf "https://gitlab.sh.nextgenwaterprediction.com/"

# Install Python virtual environment
ENV VIRTUAL_ENV=/ngencerf/ngencerf-python
ENV PATH=${VIRTUAL_ENV}/bin:${PATH}

RUN --mount=type=cache,target=/root/.cache/pip,id=pip-cache \
    set -eux && \
    python3.11 -m venv ${VIRTUAL_ENV} && \
    # Lock numpy and netcdf4 versions so t-route doesn't break
    pip3 install --upgrade pip "numpy==1.26.4" "pandas~=2.2.2"

WORKDIR /ngencerf/ngencerf-server/

# Pre-copy requirements for better caching
COPY requirements.txt .

RUN --mount=type=cache,target=/root/.cache/pip,id=pip-cache \
    set -eux && \
    pip3 install -r requirements.txt && \
    rm -f requirements.txt

# Build partitionGenerator
WORKDIR /ngencerf/ngen-sparse
RUN --mount=type=secret,id=gitlab_token \
    --mount=type=cache,target=/ngencerf/partitionGenerator_build,id=partition-generator-build \
    --mount=type=cache,target=/root/.cache/cmake,id=cmake-cache \
    set -eux && \
    # Clone only the required directories
    git clone --depth 1 --filter=blob:none --sparse https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen.git . && \
    git sparse-checkout init --cone && \
    git sparse-checkout set \
        src \
        include \
        extern \
        cmake && \
    # Configure CMake
    cmake -S /ngencerf/ngen-sparse -B /ngencerf/partitionGenerator_build \
          -DCMAKE_BUILD_TYPE=Release \
          -DNGEN_WITH_MPI=OFF \
          -DNGEN_WITH_NETCDF=OFF \
          -DNGEN_WITH_SQLITE=ON \
          -DNGEN_WITH_UDUNITS=OFF \
          -DNGEN_WITH_BMI_FORTRAN=OFF \
          -DNGEN_WITH_BMI_C=OFF \
          -DNGEN_WITH_PYTHON=OFF \
          -DNGEN_WITH_TESTS=OFF \
          -DNGEN_WITH_ROUTING=OFF \
          -DNGEN_QUIET=ON \
          -DNGEN_UPDATE_GIT_SUBMODULES=OFF \
          -DNGEN_WITH_EXTERN_ALL=OFF \
          -DNGEN_WITH_EXTERN_SLOTH=OFF \
          -DBOOST_ROOT=/opt/boost && \
    # Build partitionGenerator
    cmake --build /ngencerf/partitionGenerator_build --target partitionGenerator --parallel && \
    # Copy partitionGenerator to server root
    install -m 755 /ngencerf/partitionGenerator_build/partitionGenerator /ngencerf/ngencerf-server/ && \
    # Cleanup non-cached build artifacts
    rm -rf /ngencerf/ngen-sparse

WORKDIR /ngencerf/ngencerf-server/

# Install additional Python packages
ARG CREATE_INPUT_TAG
ARG RUN_SWE_TAG
ARG CACHE_BUST=1
# Configure Git with the GitLab token using BuildKit secret mount
RUN --mount=type=secret,id=gitlab_token \
    set -eux && \
    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-cal.git@${CREATE_INPUT_TAG}#egg=createInput&subdirectory=python/createInput" && \
    echo $CACHE_BUST && pip3 install "git+https://gitlab.sh.nextgenwaterprediction.com/NGWPC/nwm-ngen/ngen-forcing.git@${RUN_SWE_TAG}#egg=swe_processing&subdirectory=swe_processing" && \
    rm -f /root/.gitconfig && \
    pip3 cache purge

COPY cli /ngencerf/ngencerf-server/cli

# Build CLI executable in cli/dist
RUN cli/build_cli.sh

# Should parallel similar functionality in the run_cerf.sh
COPY .git .git

RUN set -eux && \
    # Get the remote URL from Git configuration
    repo_url=$(git config --get remote.origin.url) && \
    # Extract the repo name (everything after the last slash) and remove any trailing .git
    key=${repo_url##*/} && \
    key=${key%.git} && \
    # Construct the file path using the derived key
    GIT_INFO_PATH="${key}_git_info.json" && \
    jq -n \
      --arg commit_hash "$(git rev-parse HEAD)" \
      --arg branch "$(git rev-parse --abbrev-ref HEAD)" \
      --arg tags "$(git tag --points-at HEAD | tr '\n' ' ')" \
      --arg author "$(git log -1 --pretty=format:'%an')" \
      --arg commit_date "$(date -u -d @$(git log -1 --pretty=format:'%ct') +'%Y-%m-%d %H:%M:%S UTC')" \
      --arg message "$(git log -1 --pretty=format:'%s' | tr '\n' ';')" \
      --arg build_date "$(date -u +'%Y-%m-%d %H:%M:%S UTC')" \
      "{\"$key\": {commit_hash: \$commit_hash, branch: \$branch, tags: \$tags, author: \$author, commit_date: \$commit_date, message: \$message, build_date: \$build_date}}" \
      > $GIT_INFO_PATH

# Copy application code
COPY . /ngencerf/ngencerf-server/

# Remove .git directory
RUN rm -rf .git

# Copy additional configuration files
COPY ./cerfserver-docker.env /ngencerf/ngencerf-server/cerfserver.env
COPY ./cerfServer/__.env-docker-prod /ngencerf/ngencerf-server/cerfServer/.env
COPY ./cerfServer/__local_settings_prod_pw.py /ngencerf/ngencerf-server/cerfServer/local_settings.py

# Set the entry point and expose the application port
ENTRYPOINT [ "/ngencerf/ngencerf-server/runCerf.sh" ]
EXPOSE 8000
