name: ngencerf-server

services:
  ngencerf-services:
    build: 
      dockerfile: ./Dockerfile.production-pw
      context: .
      args:
        - CREATE_INPUT_TAG=development
      secrets:
        - gitlab_token
        - aws_token
    image: registry.sh.nextgenwaterprediction.com/ngwpc/nwm-ngen/ngencerf-server:prod
    pull_policy: always
    ports:
      - "8000:8000"
    volumes:
      - ../data/.ngencerf-init:/ngencerf/ngencerf-server/.init/
      - ${NGEN_CAL_DATA_PATH}:/ngencerf/data/
      - ../logs/ngencerf-server:/ngencerf/ngencerf-server/run-logs/
      - ${FORCING_DATA_S3_PATH}:${FORCING_DATA_MOUNT_PATH}
      - ${HF_DATA_S3_PATH}:${HF_DATA_MOUNT_PATH}
    environment:
      - NGEN_CAL_DATA_PATH=${NGEN_CAL_DATA_PATH}
    env_file:
      - path: ./ngencerf_services.env
        required: true 
      - path: ./ngencerf_services.override.env
        required: false

secrets:
  gitlab_token:
    file: ~/.gitlab_token
  aws_token:
    file: ./.aws_credentials
