"""
Django settings for cerfServer project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import re
from datetime import timedelta
from enum import StrEnum, auto
from pathlib import Path

from dotenv import load_dotenv

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

dotenv_path = Path(__file__).parent / '.env'
print(f'Loading values from {dotenv_path}')
load_dotenv(dotenv_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("CERF_SERVER_SECRET_KEY")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django_dbconn_retry',
    'django.contrib.staticfiles',
    'drf_spectacular',
    'calibration.apps.CalibrationConfig',
    "rest_framework",
    "rest_framework.authtoken",
    "djoser",
    "rest_framework_simplejwt",
    'corsheaders',
]

# Points to which token model should be used for authentication. In case if only stateless 
# tokens (e.g. JWT) are used in project it should be set to None.
TOKEN_MODEL = None

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'NgenCerf',
    'DESCRIPTION': 'Backend server for ngenCerf',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_currentuser.middleware.ThreadLocalUserMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
]

ROOT_URLCONF = 'cerfServer.urls'

# We should be able to get rid of this since we are not using templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = 'calibration.CustomUser'

DJOSER = {
    "SEND_CONFIRMATION_EMAIL": False,
    "SEND_ACTIVATION_EMAIL": False,
    "SET_PASSWORD_RETYPE": True,
    "UPDATE_LAST_LOGIN": True,
    "SERIALIZERS": {
        "user_create": "calibration.user_serializers.CustomUserCreateSerializer",
        "user": "calibration.user_serializers.CustomUserSerializer",
        "current_user": "calibration.user_serializers.CustomUserSerializer",
    },
}

# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html#settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'UPDATE_LAST_LOGIN': True,
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'TOKEN_OBTAIN_SERIALIZER': 'calibration.user_serializers.CustomTokenObtainPairSerializer',  # Update to your module path
}

WSGI_APPLICATION = 'cerfServer.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators


AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -----------------------------
# Hydrofabric
# -----------------------------
HYDROFABRIC_GEOPACKAGE_ENDPOINT = (True, 'hydrofabric/2.1/geopackages?gage_id={gage_id}&source={source}&domain={domain}')
HYDROFABRIC_MODULE_METADATA_ENDPOINT = (False, 'hydrofabric/2.1/modules/parameters/')
HYDROFABRIC_OBSERVATION_DATA_ENDPOINT = (True, 'hydrofabric/2.1/observational?gage_id={gage_id}&source={agency}&domain={domain}')
HYDROFABRIC_FORCING_DATA_ENDPOINT = (False, 'hydrofabric/2.1/forcing')

HYDROFABRIC_URL = os.getenv('HYDROFABRIC_URL', 'http://localhost:8001')

S3_MOUNT_POINT = Path.home() / 's3'

# -----------------------------
# Ngen/Ngen-cal Locations
# -----------------------------

# Locations for running ngen-cal

# Must match the repo root used in the docker container.
# It is not necessary for you to have local copies of the ngen and ngen-cal repos if you are using Docker
# But these directories still need to be set to reflect the directory of the repos in the docker container.
REPO_ROOT = '/ngen-app'
# Directory that Ngen is cloned into
NGEN_REPO_ROOT = str(Path(REPO_ROOT) / 'ngen')
# directory that Ngen-cal is cloned into
NGEN_CAL_REPO_ROOT = str(Path(REPO_ROOT) / 'ngen-cal')

# This must match the data location in the ngen/ngen-cal docker
# Do not change this location.  You can put your data wherever you want, but you should then create a symbolic link to /ngencerf/data
# sudo mkdir /ngencerf
# sudo ln -s ~/your/data/dir /ngencerf/data
NGEN_CAL_MOUNT_POINT = '/ngencerf/data'

NGEN_LOGGING_DIR = Path(BASE_DIR) / 'logs'
NGEN_LOGGING_DIR.mkdir(exist_ok=True)

NGEN_STATIC_DIR = Path(NGEN_CAL_MOUNT_POINT) / 'ngen-static-files'

NGEN_CAL_WORK_DIR = Path(NGEN_CAL_MOUNT_POINT) / 'ngen-cal-work'
# Directory where all the output runs are stored
NGEN_CAL_RUN_DIR = Path(NGEN_CAL_WORK_DIR) / 'run_calib'

# Directory containing the ngen-cal virtual environment
# This is used only if we are running ngen/ngen-cal locally (e.g, in AWS Workspace) and not in a separate container
NGEN_CAL_VENV = str(Path(NGEN_CAL_WORK_DIR) / 'venv.cal')


class NgenEnvironmentEnum(StrEnum):
    LOCAL = "LOCAL"
    PARALLEL_WORKS = "PARALLEL_WORKS"
    DOCKER = "DOCKER"


DOCKER_CMD = f'docker run --network host -v {NGEN_CAL_MOUNT_POINT}:/{NGEN_CAL_MOUNT_POINT} ngen-cal'

# Used when running in NGEN_ENVIRONMENT=LOCAL
RUN_NGEN_CAL_SCRIPT = os.path.join(NGEN_CAL_REPO_ROOT, 'docker', 'run-ngen-cal.sh')

NGEN_ENVIRONMENT_STR = os.getenv('NGEN_ENVIRONMENT', NgenEnvironmentEnum.LOCAL.name)
try:
    NGEN_ENVIRONMENT = NgenEnvironmentEnum[NGEN_ENVIRONMENT_STR]
except KeyError:
    # noinspection PyUnresolvedReferences
    raise SystemExit(
        f"Invalid environment value for NGEN_ENVIRONMENT: {NGEN_ENVIRONMENT_STR}.  Must be one of {', '.join([e.name for e in NgenEnvironmentEnum])}")

# -----------------------------
# Slurm 
# -----------------------------

SLURM_URL = os.getenv("SLURM_URL")
SLURM_SUBMIT_CALIBRATION_JOB_ENDPOINT = 'submit-calibration-job'
SLURM_SUBMIT_VALIDATION_JOB_ENDPOINT = 'submit-validation-job'
SLURM_JOB_STATUS_ENDPOINT = 'job-status'
SLURM_CANCEL_JOB_ENDPOINT = 'cancel-job'

# -----------------------------
# Logging
# -----------------------------
print(f"Logging files will be created at {BASE_DIR}")
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'root': {
        'handlers': ['console', 'file'],
        'level': 'DEBUG'
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {funcName} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {funcName} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'DEBUG',
            'class': 'cerfServer.timed_rotating_file_handler.CustomTimedRotatingFileHandler',  # Use TimedRotatingFileHandler
            'filename': Path(NGEN_LOGGING_DIR) / 'cerfServer.log',
            'when': 'midnight',  # Rotate the file every day at midnight
            'interval': 1,  # Rotate every 1 day
            'backupCount': 10,  # Keep 10 days worth of logs (adjust as needed)
            'formatter': 'verbose',
            'encoding': 'utf-8',
        }
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False  # Prevents these logs from reaching the root logger (avoids duplication)
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # Prevents these logs from reaching the root logger (avoids duplication)
        },
        'djoser': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # Prevents these logs from reaching the root logger (avoids duplication)
        },
        'rest_framework_simplejwt': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,  # Prevents these logs from reaching the root logger (avoids duplication)

        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # Prevents these logs from reaching the root logger (avoids duplication)
        },

        # Add these loggers for 'requests' and 'urllib3'
        'requests': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # Prevents these logs from reaching the root logger (avoids duplication)
        },
        'urllib3': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,  # Prevents these logs from reaching the root logger (avoids duplication)
        },
        'calibration': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,  # Prevents these logs from reaching the root logger (avoids duplication)
        },
        'cerfServer': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,  # Prevents these logs from reaching the root logger (avoids duplication)
        },
    }
}

# This needs to be at the end of settings.py
try:
    from .local_settings import *
except ImportError:
    print('local_settings.py not found')
