# Generated by Django 5.0.6 on 2024-07-17 18:59

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('run_date', models.DateTimeField(null=True)),
                ('time_range_start', models.DateTimeField(null=True)),
                ('time_range_end', models.DateTimeField(null=True)),
                ('calibration_start_period', models.DateTimeField(null=True)),
                ('calibration_end_period', models.DateTimeField(null=True)),
                ('calibration_eval_start_period', models.DateTimeField(null=True)),
                ('calibration_eval_end_period', models.DateTimeField(null=True)),
                ('streamflow_threshold', models.FloatField(null=True)),
                ('hydrofabric_gpkg_path', models.TextField(null=True)),
                ('forcing_path', models.TextField()),
                ('forcing_user_filename', models.TextField(null=True)),
                ('forcing_source', models.TextField()),
                ('observational_path', models.TextField(null=True)),
                ('formulation_name', models.TextField(null=True)),
                ('plot_frequency', models.IntegerField(null=True)),
                ('run_type', models.TextField(null=True)),
                ('ngen_commit_hash', models.BinaryField(null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calibration_run',
            },
        ),
        migrations.CreateModel(
            name='CalibrationFormulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('name', models.TextField()),
                ('groups', models.TextField()),
                ('used_by_calibration_run', models.BooleanField(default=False)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun')),
            ],
            options={
                'db_table': 'calibration_formulation',
            },
        ),
        migrations.CreateModel(
            name='CalibrationSlothParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('param_name', models.TextField()),
                ('param_count', models.IntegerField()),
                ('param_type', models.TextField()),
                ('param_units', models.TextField()),
                ('param_location', models.TextField()),
                ('param_value', models.FloatField()),
                ('maps_to_variable_name', models.TextField()),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('maps_to_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationformulation')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calibration_sloth_param',
            },
        ),
        migrations.CreateModel(
            name='CalibrationStopCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('ordinal', models.IntegerField()),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calibration_stop_criteria',
            },
        ),
        migrations.CreateModel(
            name='CalibrationTuneParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField()),
                ('data_type', models.TextField()),
                ('default_value', models.FloatField()),
                ('initial_value', models.FloatField()),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('calibratable', models.BooleanField(default=False)),
                ('calibration_formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationformulation')),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calibration_tune_parameter',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.TextField(unique=True)),
                ('forcing_url', models.TextField(null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Gage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('gage_id', models.TextField(unique=True)),
                ('agency', models.TextField()),
                ('station_name', models.TextField()),
                ('site_type', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('lat_long_accuracy', models.TextField()),
                ('lat_long_datum', models.TextField()),
                ('altitude', models.FloatField(null=True)),
                ('altitude_accuracy', models.TextField(null=True)),
                ('altitude_datum', models.TextField(null=True)),
                ('huc', models.TextField()),
                ('drainage_area', models.FloatField(null=True)),
                ('contrib_drainage_area', models.FloatField(null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.domain')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gage',
            },
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='gage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.gage'),
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('iteration_num', models.IntegerField()),
                ('realization_filename', models.TextField()),
                ('calibration_output_variable_value', models.FloatField()),
                ('best', models.BooleanField(default=False)),
                ('calibration_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iteration',
            },
        ),
        migrations.CreateModel(
            name='IterationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('iteration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.iteration')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iteration_result',
            },
        ),
        migrations.CreateModel(
            name='IterationTuneParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.TextField()),
                ('tuned_value', models.FloatField()),
                ('calibration_tune_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationtuneparameter')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.iteration')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'iteration_tune_parameter',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.TextField(unique=True)),
                ('categorical_metric', models.BooleanField(default=False)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metric',
            },
        ),
        migrations.CreateModel(
            name='IterationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('iteration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.iteration')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.metric')),
            ],
            options={
                'db_table': 'iteration_metric',
            },
        ),
        migrations.CreateModel(
            name='CalibrationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objective_function', models.BooleanField(default=False)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.metric')),
            ],
            options={
                'db_table': 'calibration_metric',
            },
        ),
        migrations.CreateModel(
            name='ModuleOutputVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('name', models.TextField()),
                ('data_type', models.TextField()),
                ('calibration_formulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationformulation')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'module_output_variable',
            },
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='module_output_variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.moduleoutputvariable'),
        ),
        migrations.CreateModel(
            name='NgenCalFormulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('name', models.TextField(unique=True)),
                ('modules', models.TextField()),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ngen_cal_formulation',
            },
        ),
        migrations.CreateModel(
            name='ObservationalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.TextField(unique=True)),
                ('url', models.TextField(null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'observational_source',
            },
        ),
        migrations.AddField(
            model_name='gage',
            name='observational_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.observationalsource'),
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.TextField(unique=True)),
                ('stop_criteria_name', models.TextField()),
                ('stop_criteria_data_type', models.TextField()),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'optimization',
            },
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='optimization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.optimization'),
        ),
        migrations.CreateModel(
            name='OptimizationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.TextField()),
                ('data_type', models.TextField()),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('optimization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.optimization')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'optimization_input',
            },
        ),
        migrations.CreateModel(
            name='CalibrationOptimizationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun')),
                ('optimization_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.optimizationinput')),
            ],
            options={
                'db_table': 'calibration_optimization_input',
            },
        ),
        migrations.CreateModel(
            name='PlotDefinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.TextField(unique=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plot_definitions',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(unique=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.status'),
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('validation_start_period', models.DateTimeField()),
                ('validation_end_period', models.DateTimeField()),
                ('validation_eval_start_period', models.DateTimeField()),
                ('validation_eval_end_period', models.DateTimeField()),
                ('calibration_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='calibration.calibrationrun')),
                ('calibration_run_tune_parameters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_tune_parameters', to='calibration.calibrationrun')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.status')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_run',
            },
        ),
        migrations.AddConstraint(
            model_name='calibrationformulation',
            constraint=models.UniqueConstraint(fields=('name', 'calibration_run'), name='calibration_formulation__name__calibration_run__unique'),
        ),
        migrations.AddConstraint(
            model_name='calibrationtuneparameter',
            constraint=models.UniqueConstraint(fields=('name', 'calibration_formulation', 'calibration_run'), name='calibration_tune_parameter__name__calibration_formulation__unique'),
        ),
        migrations.AddConstraint(
            model_name='moduleoutputvariable',
            constraint=models.UniqueConstraint(fields=('name', 'calibration_formulation'), name='module_output_variable__name__calibration_formulation__unique'),
        ),
        migrations.AddConstraint(
            model_name='optimizationinput',
            constraint=models.UniqueConstraint(fields=('name', 'optimization'), name='optimization_input__name__optimization__unique'),
        ),
    ]
