# Generated by Django 5.0.6 on 2024-07-01 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('time_range_start', models.DateTimeField()),
                ('time_range_end', models.DateTimeField()),
                ('calibration_start_period', models.DateTimeField()),
                ('calibration_end_period', models.DateTimeField()),
                ('calibration_eval_start_period', models.DateTimeField()),
                ('calibration_eval_end_period', models.DateTimeField()),
                ('hydrofabric_gpkg_path', models.TextField()),
                ('forcing_path', models.TextField()),
                ('forcing_user_filename', models.TextField()),
                ('forcing_source', models.TextField()),
                ('observational_path', models.TextField()),
                ('seed', models.IntegerField()),
                ('formulation_name', models.TextField()),
                ('plot_frequency', models.IntegerField()),
                ('run_type', models.TextField()),
            ],
            options={
                'db_table': 'calibration_run',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
                ('forcing_url', models.TextField(null=True)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'metric',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
                ('ngen_cal_active', models.BooleanField()),
            ],
            options={
                'db_table': 'module',
            },
        ),
        migrations.CreateModel(
            name='ModuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'module_group',
            },
        ),
        migrations.CreateModel(
            name='NgenCalFormulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('name', models.TextField(unique=True)),
                ('modules', models.TextField()),
            ],
            options={
                'db_table': 'ngen_cal_formulation',
            },
        ),
        migrations.CreateModel(
            name='ObservationalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
                ('url', models.TextField(null=True)),
            ],
            options={
                'db_table': 'observational_source',
            },
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
                ('stop_criteria_name', models.TextField()),
                ('stop_criteria_data_type', models.TextField()),
            ],
            options={
                'db_table': 'optimization',
            },
        ),
        migrations.CreateModel(
            name='PlotDefinitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'plot_definitions',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='CalibrationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_function', models.BooleanField()),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
                ('metric_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.metric')),
            ],
            options={
                'db_table': 'calibration_metric',
            },
        ),
        migrations.CreateModel(
            name='CalibrationInitialParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('default_value', models.FloatField()),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
                ('module_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.module')),
            ],
            options={
                'db_table': 'calibration_initial_parameter',
            },
        ),
        migrations.CreateModel(
            name='CalibrationSlothParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.TextField()),
                ('param_count', models.IntegerField()),
                ('param_type', models.TextField()),
                ('param_units', models.TextField()),
                ('param_location', models.TextField()),
                ('param_value', models.FloatField()),
                ('maps_to_variable_name', models.TextField()),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
            ],
            options={
                'db_table': 'calibration_sloth_param',
            },
        ),
        migrations.CreateModel(
            name='CalibrationStopCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('value', models.IntegerField()),
                ('ordinal', models.IntegerField()),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
            ],
            options={
                'db_table': 'calibration_stop_criteria',
            },
        ),
        migrations.CreateModel(
            name='CalibrationTuneParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum', models.FloatField()),
                ('maximum', models.FloatField()),
                ('initial', models.FloatField()),
                ('calibration_initial_parameter_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationinitialparameter')),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
            ],
            options={
                'db_table': 'calibration_tune_parameter',
            },
        ),
        migrations.CreateModel(
            name='Gage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('gage_id', models.TextField(unique=True)),
                ('agency', models.TextField()),
                ('station_name', models.TextField()),
                ('site_type', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('lat_long_accuracy', models.TextField()),
                ('lat_long_datum', models.TextField()),
                ('huc', models.TextField()),
                ('drainage_area', models.FloatField()),
                ('contrib_drainage_area', models.FloatField()),
                ('domain_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.domain')),
            ],
            options={
                'db_table': 'gage',
            },
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='gage_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.gage'),
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_num', models.IntegerField()),
                ('realization_filename', models.TextField()),
                ('calibration_output_variable_value', models.FloatField()),
                ('best', models.BooleanField()),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
            ],
            options={
                'db_table': 'iteration',
            },
        ),
        migrations.CreateModel(
            name='IterationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_metric_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationmetric')),
                ('iteration_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.iteration')),
            ],
            options={
                'db_table': 'iteration_metric',
            },
        ),
        migrations.CreateModel(
            name='IterationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.iteration')),
            ],
            options={
                'db_table': 'iteration_result',
            },
        ),
        migrations.CreateModel(
            name='IterationTuneParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.TextField()),
                ('tuned_value', models.FloatField()),
                ('calibration_initial_parameter_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationinitialparameter')),
                ('iteration_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.iteration')),
            ],
            options={
                'db_table': 'iteration_tune_parameter',
            },
        ),
        migrations.CreateModel(
            name='CalibrationMetricInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.TextField()),
                ('value', models.FloatField()),
                ('calibration_metric_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationmetric')),
                ('metric_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.metric')),
            ],
            options={
                'db_table': 'calibration_metric_input',
            },
        ),
        migrations.CreateModel(
            name='MetricInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
                ('data_type', models.TextField()),
                ('default_value', models.TextField()),
                ('metric_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.metric')),
            ],
            options={
                'db_table': 'metric_input',
            },
        ),
        migrations.CreateModel(
            name='CalibrationFormulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('module_commit_hash', models.BinaryField()),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
                ('module_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.module')),
            ],
            options={
                'db_table': 'calibration_formulation',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(to='calibration.modulegroup'),
        ),
        migrations.CreateModel(
            name='ModuleInputVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
                ('data_type', models.TextField()),
                ('module_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.module')),
            ],
            options={
                'db_table': 'module_input_variable',
            },
        ),
        migrations.CreateModel(
            name='ModuleOutputVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
                ('data_type', models.TextField()),
                ('module_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.module')),
            ],
            options={
                'db_table': 'module_output_variable',
            },
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='module_output_variable_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.moduleoutputvariable'),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='optimization_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.optimization'),
        ),
        migrations.CreateModel(
            name='OptimizationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('name', models.TextField(unique=True)),
                ('optimization_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.optimization')),
            ],
            options={
                'db_table': 'optimization_input',
            },
        ),
        migrations.CreateModel(
            name='CalibrationOptimizationInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun')),
                ('optimization_input_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.optimizationinput')),
            ],
            options={
                'db_table': 'calibration_optimization_input',
            },
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='status_pk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.status'),
        ),
        migrations.CreateModel(
            name='ValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('validation_start_period', models.DateTimeField()),
                ('validation_end_period', models.DateTimeField()),
                ('validation_eval_start_period', models.DateTimeField()),
                ('validation_eval_end_period', models.DateTimeField()),
                ('calibration_run_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to='calibration.calibrationrun')),
                ('calibration_run_pk_tune_parameters', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_tune_parameters', to='calibration.calibrationrun')),
                ('status_pk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.status')),
            ],
            options={
                'db_table': 'validation_run',
            },
        ),
    ]
