# Generated by Django 5.0.6 on 2024-07-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observationalsource',
            name='url',
        ),
    ]
