# Generated by Django 5.1.3 on 2024-12-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetrics',
            name='cpu_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='num_cpus',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='slurm_job_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
