# Generated by Django 5.0.7 on 2024-08-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='ngen_cal_commit_hash',
            field=models.BinaryField(null=True),
        ),
    ]
