# Generated by Django 5.1b1 on 2024-08-01 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='forcing_path',
            new_name='forcing_dir_path',
        ),
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='forcing_user_filename',
            new_name='forcing_user_dir',
        ),
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='observational_path',
            new_name='observational_file_path',
        ),
    ]
