# Generated by Django 5.0.6 on 2024-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='run_date',
            field=models.DateTimeField(null=True),
        ),
    ]
