# Generated by Django 5.1.1 on 2024-10-02 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='run_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status'),
        ),
    ]
