# Generated by Django 5.1 on 2024-08-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='forcing_dir_path',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='hydrofabric_gpkg_path',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='observational_file_path',
        ),
    ]
