# Generated by Django 5.0.6 on 2024-07-17 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='objective_function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.metric'),
        ),
        migrations.DeleteModel(
            name='CalibrationMetric',
        ),
    ]
