# Generated by Django 5.1.2 on 2024-10-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_disk_read',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_disk_write',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_rss',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
