# Generated by Django 5.1.3 on 2024-12-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastcycle',
            name='internal_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
