# Generated by Django 5.1.2 on 2024-10-16 20:48

import calibration.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(height_field='height', null=True, upload_to=calibration.models.user_model.user_directory_path, width_field='width'),
        ),
    ]
