# Generated by Django 5.1b1 on 2024-07-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationtuneparameter',
            name='calibratable',
        ),
    ]
