# Generated by Django 5.0.6 on 2024-07-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationformulation',
            name='used_by_calibration_run',
            field=models.BooleanField(default=False),
        ),
    ]
