# Generated by Django 5.1.1 on 2024-09-10 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0002_alter_iteration_calibration_run_and_more'), ('calibration', '0003_calibrationrun_is_deleted')]

    dependencies = [
        ('calibration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='calibration_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
        ),
        migrations.AlterField(
            model_name='iterationmetric',
            name='iteration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.iteration'),
        ),
        migrations.AlterField(
            model_name='iterationmetric',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.metric'),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='calibration_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='calibration.calibrationrun'),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
