# Generated by Django 5.1.2 on 2024-10-27 03:02

from django.db import migrations


def update_upload_entries(apps, schema_editor):
    # Get the models
    ForcingSource = apps.get_model('calibration', 'ForcingSource')
    ObservationalSource = apps.get_model('calibration', 'ObservationalSource')
    GeopackageSource = apps.get_model('calibration', 'GeopackageSource')

    # Update "Upload" entries to "User Upload" in each model
    ForcingSource.objects.filter(name="Upload").update(name="User Upload")
    ObservationalSource.objects.filter(name="Upload").update(name="User Upload")
    GeopackageSource.objects.filter(name="Upload").update(name="User Upload")


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0002_alter_performancemetrics_max_disk_read_and_more'),
    ]

    operations = [
        migrations.RunPython(update_upload_entries),
    ]
