# Generated by Django 5.1.1 on 2024-10-03 19:55

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_validationrun_run_date_alter_validationrun_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_id', models.CharField(max_length=50)),
                ('elapsed_time', models.DurationField()),
                ('num_cpus', models.IntegerField()),
                ('cpu_time', models.DurationField()),
                ('max_rss', models.CharField(max_length=50)),
                ('max_disk_read', models.CharField(max_length=50)),
                ('max_disk_write', models.CharField(max_length=50)),
                ('reserved_time', models.DurationField(blank=True, null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_metrics',
            },
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='performance_metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='calibration.performancemetrics'),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='performance_metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='calibration.performancemetrics'),
        ),
    ]
