# Generated by Django 5.1b1 on 2024-08-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_rename_forcing_path_calibrationrun_forcing_dir_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationtuneparameter',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
