# Generated by Django 5.1b1 on 2024-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_remove_calibrationtuneparameter_calibratable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='formulation_name',
            new_name='ngen_formulation_name',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='user_formulation_name',
            field=models.TextField(null=True),
        ),
    ]
