# Generated by Django 5.1 on 2024-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_remove_calibrationrun_forcing_dir_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='forcing_hydrofabric_dir_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='hydrofabric_gpkg_path',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='observational_hydrofabric_file_path',
            field=models.TextField(null=True),
        ),
    ]
