# Generated by Django 5.0.6 on 2024-07-08 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_alter_calibrationformulation_used_by_calibration_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationformulation',
            name='calibration_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun'),
        ),
    ]
