# Generated by Django 5.0.6 on 2024-07-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_calibrationrun_run_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricinput',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='observationalsource',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='optimization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='optimizationinput',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plotdefinitions',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
