# Generated by Django 5.1.2 on 2024-10-16 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_customuser_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
