# Generated by Django 5.1.2 on 2024-10-14 15:51

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_alter_validationrun_iteration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ValidationMetric',
            new_name='ValidationMetrics',
        ),
        migrations.CreateModel(
            name='NWMRetrospectiveMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_type', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('metric_value', models.FloatField()),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.calibrationrun')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.metric')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'nwm_retrospective_metrics',
                'constraints': [models.UniqueConstraint(fields=('metric', 'period', 'run_type', 'calibration_run'), name='validation_metric__metric__period__run_type__calibration_run__unique')],
            },
        ),
    ]
