# Generated by Django 5.1b1 on 2024-07-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_forcingsource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='forcing_url',
        ),
    ]
