# Generated by Django 5.1.1 on 2024-10-01 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_remove_modulegroup_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationformulation',
            name='description',
        ),
        migrations.AlterField(
            model_name='calibrationslothparam',
            name='maps_to_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.module'),
        ),
    ]
