# Generated by Django 5.0.7 on 2024-08-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_remove_gage_observational_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdefinitions',
            name='filename_mask',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
