# Generated by Django 5.1.3 on 2024-12-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_alter_performancemetrics_cpu_time_and_more'),
    ]

    operations = [
        # Step 1: Drop the generated column
        migrations.RunSQL(
            sql="ALTER TABLE performance_metrics DROP COLUMN io_throughput;",
            reverse_sql="ALTER TABLE performance_metrics ADD COLUMN io_throughput FLOAT GENERATED ALWAYS AS "
                        "((COALESCE(max_disk_read, 0) + COALESCE(max_disk_write, 0)) / NULLIF(EXTRACT(EPOCH FROM elapsed_time), 0)) STORED;"
        ),

        # Step 2: Alter the column types
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_disk_read',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_disk_write',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_rss',
            field=models.FloatField(null=True),
        ),

        # Step 3: Recreate the generated column
        migrations.RunSQL(
            sql="ALTER TABLE performance_metrics ADD COLUMN io_throughput FLOAT GENERATED ALWAYS AS "
                "((COALESCE(max_disk_read, 0) + COALESCE(max_disk_write, 0)) / NULLIF(EXTRACT(EPOCH FROM elapsed_time), 0)) STORED;",
            reverse_sql="ALTER TABLE performance_metrics DROP COLUMN io_throughput;"
        ),
    ]
