# Generated by Django 5.0.7 on 2024-08-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_calibrationrun_ngen_cal_commit_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='ngen_cal_commit_hash',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='ngen_commit_hash',
            field=models.TextField(null=True),
        ),
    ]
