# Generated by Django 5.0.6 on 2024-07-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_calibrationformulation_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleinputvariable',
            old_name='module_pk',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='moduleoutputvariable',
            old_name='module_pk',
            new_name='module',
        ),
    ]
