# Generated by Django 5.1.1 on 2024-10-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_performancemetrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationformulation',
            name='calibration_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
        ),
    ]
