# Generated by Django 5.1.1 on 2024-10-04 00:52

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0004_alter_iterationmetric_metric_value_and_more'), ('calibration', '0005_remove_validationglobalmetric_validation_global_metric__metric__period__calibration_run__unique_and_')]

    dependencies = [
        ('calibration', '0003_performancemetrics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='iterationmetric',
            name='metric_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ValidationGlobalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_type', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('metric_value', models.FloatField()),
                ('calibration_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.calibrationrun')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.metric')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_global_metric',
                'constraints': [models.UniqueConstraint(fields=('metric', 'period', 'run_type', 'calibration_run'), name='validation_global_metric__metric__period__run_type__calibration_run__unique')],
            },
        ),
    ]
