# Generated by Django 5.1b1 on 2024-07-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_rename_formulation_name_calibrationrun_ngen_formulation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='use_sloth',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
