# Generated by Django 5.1.2 on 2024-11-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_update_upload_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteration',
            old_name='calibration_output_variable_value',
            new_name='objective_function_value',
        ),
    ]
