# Generated by Django 5.1.2 on 2024-10-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_rename_validationmetric_validationmetrics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterationresult',
            name='filename',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
