# Generated by Django 5.0.6 on 2024-07-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_rename_module_pk_moduleinputvariable_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gage',
            name='altitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gage',
            name='altitude_accuracy',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gage',
            name='altitude_datum',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gage',
            name='contrib_drainage_area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gage',
            name='drainage_area',
            field=models.FloatField(null=True),
        ),
    ]
