# Generated by Django 5.1.3 on 2024-12-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_alter_forecastcycle_internal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastcycle',
            name='internal_name',
            field=models.CharField(max_length=50),
        ),
    ]
