# Generated by Django 5.0.6 on 2024-07-16 14:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_metricinput_is_active_alter_calibrationrun_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricinput',
            name='name',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='metricinput',
            constraint=models.UniqueConstraint(fields=('name', 'metric'), name='metric_input__name__metric__unique'),
        ),
    ]
