# Generated by Django 5.1b1 on 2024-07-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_remove_domain_forcing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='forcing_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='forcing_source',
            field=models.TextField(null=True),
        ),
    ]
