# Generated by Django 5.1 on 2024-08-28 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_calibrationrun_forcing_hydrofabric_dir_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='observational_user_filename',
            new_name='observational_user_file_path',
        ),
    ]
