# Generated by Django 5.0.7 on 2024-08-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_plotdefinitions_filename_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='event_based',
            field=models.BooleanField(default=False),
        ),
    ]
