# Generated by Django 5.1.1 on 2024-09-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0004_calibrationformulation_bmi_config_path_and_more'), ('calibration', '0005_rename_realization_filename_calibrationrun_realization_file_path'), ('calibration', '0006_rename_calibration_tune_parameter_iterationparameter_calibration_parameter')]

    dependencies = [
        ('calibration', '0002_alter_iteration_calibration_run_and_more_squashed_0003_calibrationrun_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationformulation',
            name='bmi_config_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationformulation',
            name='groups',
            field=models.TextField(max_length=50),
        ),
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='realization_filename',
            new_name='realization_file_path',
        ),
        migrations.RenameField(
            model_name='iterationparameter',
            old_name='calibration_tune_parameter',
            new_name='calibration_parameter',
        ),
    ]
