# Generated by Django 5.0.7 on 2024-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0004_metric_event_based'), ('calibration', '0005_calibrationrun_peak_flow_threshold')]

    dependencies = [
        ('calibration', '0003_plotdefinitions_filename_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='event_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='peak_flow_threshold',
            field=models.FloatField(null=True),
        ),
    ]
