# Generated by Django 5.1.1 on 2024-09-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_alter_iteration_calibration_run_and_more_squashed_0003_calibrationrun_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationformulation',
            name='bmi_config_path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationformulation',
            name='groups',
            field=models.TextField(max_length=50),
        ),
    ]
