# Generated by Django 5.1b1 on 2024-07-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_calibrationrun_use_sloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='use_sloth',
            field=models.BooleanField(default=False),
        ),
    ]
