# Generated by Django 5.1.2 on 2024-10-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_iterationresult_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulegroup',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
