# Generated by Django 5.0.6 on 2024-07-16 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_alter_metricinput_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricinput',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='calibration.metric'),
        ),
    ]
