# Generated by Django 5.0.6 on 2024-07-09 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_calibrationrun_owner_validationrun_owner_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleInputVariable',
        ),
    ]
