# Generated by Django 5.1.4 on 2025-01-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_alter_forecastcycle_internal_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='objective_function',
            field=models.BooleanField(default=False),
        ),
    ]
