# Generated by Django 5.1.3 on 2024-12-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_alter_performancemetrics_max_disk_read_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='forcing_hydrofabric_dir_path',
            new_name='forcing_eds_dir_path',
        ),
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='geopackage_hydrofabric_file_path',
            new_name='geopackage_eds_file_path',
        ),
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='observational_hydrofabric_file_path',
            new_name='observational_eds_file_path',
        ),
    ]
