# Generated by Django 5.1b1 on 2024-07-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_alter_calibrationrun_forcing_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='got_module_data_from_hydrofabric',
        ),
        migrations.AlterField(
            model_name='moduleoutputvariable',
            name='calibration_formulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_variables', to='calibration.calibrationformulation'),
        ),
    ]
