# Generated by Django 5.1.1 on 2024-09-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_calibrationformulation_bmi_config_path_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='realization_filename',
            new_name='realization_file_path',
        ),
    ]
