# Generated by Django 5.1 on 2024-09-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0005_rename_hydrofabric_gpkg_path_calibrationrun_geopackage_hydrofabric_path_and_more'), ('calibration', '0006_rename_geopackage_user_path_calibrationrun_geopackage_user_file_path')]

    dependencies = [
        ('calibration', '0004_rename_observational_user_filename_calibrationrun_observational_user_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='hydrofabric_gpkg_path',
            new_name='geopackage_hydrofabric_path',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='geopackage_user_file_path',
            field=models.TextField(null=True),
        ),
    ]
