# Generated by Django 5.0.6 on 2024-07-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_gage_altitude_gage_altitude_accuracy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gage',
            old_name='domain_pk',
            new_name='domain',
        ),
    ]
