# Generated by Django 5.1.2 on 2024-11-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_rename_calibration_output_variable_value_iteration_objective_function_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='job_genesis',
            field=models.CharField(default='gui', max_length=20),
            preserve_default=False,
        ),
    ]
