# Generated by Django 5.0.7 on 2024-08-14 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_metric_event_based_squashed_0005_calibrationrun_peak_flow_threshold'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteration',
            name='realization_filename',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='realization_filename',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='iteration',
            name='worker',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iterationmetric',
            name='metric_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iteration',
            name='calibration_run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='calibration.calibrationrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iteration',
            name='iteration_num',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='iterationmetric',
            name='iteration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='calibration.iteration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iterationmetric',
            name='metric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='calibration.metric'),
            preserve_default=False,
        ),
    ]
