# Generated by Django 5.0.6 on 2024-07-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_rename_domain_pk_gage_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gage',
            name='altitude',
            field=models.FloatField(null=True),
        ),
    ]
