# Generated by Django 5.1.1 on 2024-10-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_alter_calibrationformulation_calibration_run'),
        ('calibration', '0004_alter_iterationmetric_metric_value_and_more_squashed_0005_remove_validationglobalmetric_validation_global_metric__metric__period__calibration_run__unique_and_'),
    ]

    operations = [
    ]
