# Generated by Django 5.1b1 on 2024-07-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_alter_calibrationrun_use_sloth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleoutputvariable',
            name='data_type',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='calibration_run_tune_parameters',
        ),
        migrations.AddField(
            model_name='validationrun',
            name='iteration',
            field=models.IntegerField(null=True),
        ),
    ]
