# Generated by Django 5.1.4 on 2025-01-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_metric_objective_function'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iterationparameter',
            name='data_type',
        ),
    ]
