# Generated by Django 5.1.2 on 2024-11-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_calibrationrun_job_genesis'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE calibration_run SET job_genesis = 'gui' WHERE job_genesis = 'JobGenesis.GUI';",
            reverse_sql="UPDATE calibration_run SET job_genesis = 'JobGenesis.GUI' WHERE job_genesis = 'gui';"
        ),
    ]