# Generated by Django 5.1b1 on 2024-07-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_remove_calibrationrun_got_module_data_from_hydrofabric_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationstopcriteria',
            name='ordinal',
        ),
    ]
