# Generated by Django 5.1.3 on 2024-12-09 20:03

import calibration.models.performance_metrics
import calibration.models.performance_metrics
import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models
from django.db.models import F, Value, FloatField, ExpressionWrapper, Case, When
from django.db.models.functions import Coalesce, NullIf


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_rename_forcing_hydrofabric_dir_path_calibrationrun_forcing_eds_dir_path_and_more'),
    ]

    operations = [
        # Step 1: Remove the existing `io_throughput` field
        migrations.RemoveField(
            model_name='performancemetrics',
            name='io_throughput',
        ),
        # Step 2: Add the `io_throughput` field back with the new definition
        migrations.AddField(
            model_name='performancemetrics',
            name='io_throughput',
            field=models.GeneratedField(
                db_persist=True,
                output_field=FloatField(),  # Specify the output field type
                expression=Case(
                    # If any relevant field is NULL, io_throughput should also be NULL
                    When(
                        models.Q(
                            max_disk_read__isnull=True,
                            max_disk_write__isnull=True,
                            elapsed_time__isnull=True,
                            _connector='OR',
                        ),
                        then=Value(None),
                    ),
                    # Otherwise, calculate io_throughput
                    default=ExpressionWrapper(
                        (Coalesce(F('max_disk_read'), Value(0)) + Coalesce(F('max_disk_write'), Value(0))) /
                        NullIf(calibration.models.performance_metrics.ExtractEpoch(F('elapsed_time')), 0),
                        output_field=FloatField(),
                    ),
                    output_field=FloatField(),
                ),
            ),
        ),
    ]
