# Generated by Django 5.0.6 on 2024-07-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_alter_metricinput_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricinput',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.metric'),
        ),
    ]
