# Generated by Django 5.0.6 on 2024-07-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_delete_moduleinputvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleoutputvariable',
            name='is_active',
        ),
        migrations.AlterModelTable(
            name='moduleoutputvariable',
            table='module_output_variable',
        ),
    ]
