# Generated by Django 5.0.6 on 2024-07-09 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_remove_moduleoutputvariable_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calibrationformulation',
            name='calibration_formulation_name_run_unique',
        ),
        migrations.AddConstraint(
            model_name='calibrationformulation',
            constraint=models.UniqueConstraint(fields=('name', 'calibration_run'), name='calibration_formulation__name__calibration_run__unique'),
        ),
        migrations.AddConstraint(
            model_name='moduleoutputvariable',
            constraint=models.UniqueConstraint(fields=('name', 'calibration_formulation'), name='module_output_variable__name__calibration_formulation__unique'),
        ),
    ]
