# Generated by Django 5.0.7 on 2024-08-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_remove_iteration_realization_filename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteration',
            old_name='best',
            new_name='best_for_worker',
        ),
        migrations.AddField(
            model_name='iteration',
            name='best_overall',
            field=models.BooleanField(default=False),
        ),
    ]
