# Generated by Django 5.1b1 on 2024-07-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_remove_moduleoutputvariable_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationtuneparameter',
            name='default_value',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='observational_source',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='observational_user_filename',
            field=models.TextField(null=True),
        ),
    ]
