# Generated by Django 5.1 on 2024-09-03 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_rename_hydrofabric_gpkg_path_calibrationrun_geopackage_hydrofabric_path_and_more_squashed_0006_rename_geopackage_user_path_calibrationrun_geopackage_user_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='forcing_user_dir',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='geopackage_user_file_path',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='observational_user_file_path',
        ),
    ]
