# Generated by Django 5.1b1 on 2024-07-22 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_remove_calibrationstopcriteria_ordinal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='gage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='calibration.gage'),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='module_output_variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='calibration.moduleoutputvariable'),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='objective_function',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='calibration.metric'),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='optimization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='calibration.optimization'),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status'),
        ),
    ]
