# Generated by Django 5.1.2 on 2024-11-07 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('calibration', '0006_fix_job_genesis_value'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE geopackage_source SET name = 'Data Services' WHERE name = 'EHS';",
            reverse_sql="UPDATE geopackage_source SET name = 'EHS' WHERE name = 'Data Services';"
        ),
    ]
