# Generated by Django 5.0.6 on 2024-07-16 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_alter_metricinput_metric'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationinput',
            name='data_type',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optimizationinput',
            name='optimization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.optimization'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='optimizationinput',
            constraint=models.UniqueConstraint(fields=('name', 'optimization'), name='optimization_input__name__optimization__unique'),
        ),
    ]
