# Generated by Django 5.1.1 on 2024-09-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_calibrationformulation_bmi_config_path_and_more_squashed_0006_rename_calibration_tune_parameter_iterationparameter_calibration_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationparameter',
            name='units',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
