# Generated by Django 5.1.4 on 2025-01-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_remove_iterationparameter_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastforcingdownloadrun',
            name='ngen_forcing_commit_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='ngen_commit_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='ngen_forecast_commit_hash',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
