# Generated by Django 5.1.3 on 2024-12-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_alter_performancemetrics_io_throughput'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationformulation',
            name='bmi_config_path',
        ),
        migrations.RemoveField(
            model_name='performancemetrics',
            name='io_throughput',
        ),
    ]
