# Generated by Django 5.1.1 on 2024-10-08 19:53

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_merge_20241004_2005'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancemetrics',
            old_name='job_id',
            new_name='slurm_job_id',
        ),
        migrations.AddField(
            model_name='validationrun',
            name='ngen_cal_commit_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='ngen_commit_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='slurm_job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='validation_type',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='performance_metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.performancemetrics'),
        ),
        migrations.CreateModel(
            name='ValidationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_type', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('metric_value', models.FloatField()),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.metric')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('validation_run', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.validationrun')),
            ],
            options={
                'db_table': 'validation_metric',
                'constraints': [models.UniqueConstraint(fields=('metric', 'period', 'run_type', 'validation_run'), name='validation_metric__metric__period__run_type__validation_run__unique')],
            },
        ),
    ]
