# Generated by Django 5.0.6 on 2024-07-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_alter_gage_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='groups',
            field=models.ManyToManyField(db_table='module_group_members', to='calibration.modulegroup'),
        ),
    ]
