# Generated by Django 5.0.6 on 2024-07-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_alter_module_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gage',
            name='domain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.domain'),
        ),
    ]
