# Generated by Django 5.0.7 on 2024-08-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_rename_best_iteration_best_for_worker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='run_type',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='automatic_validation',
            field=models.BooleanField(default=False),
        ),
    ]
