# Generated by Django 5.0.6 on 2024-07-09 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_remove_calibrationformulation_calibration_formulation_name_run_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationformulation',
            name='calibration_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moduleoutputvariable',
            name='calibration_formulation',
            field=models.ForeignKey(default=297, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationformulation'),
            preserve_default=False,
        ),
    ]
