# Generated by Django 5.1.1 on 2024-09-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0008_calibrationrun_job_data_dir'), ('calibration', '0009_alter_calibrationrun_job_data_dir')]

    dependencies = [
        ('calibration', '0007_remove_calibrationrun_forcing_user_dir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='job_data_dir',
            field=models.CharField(default='', max_length=50),
        ),
    ]
