# Generated by Django 5.0.6 on 2024-07-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_optimizationinput_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optimizationinput',
            name='name',
            field=models.TextField(),
        ),
    ]
