# Generated by Django 5.1.4 on 2025-02-20 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_forecastforcingdownloadrun_ngen_forcing_commit_hash_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='is_deleted',
            new_name='is_archived',
        ),
    ]
