# Generated by Django 5.1.2 on 2024-11-14 16:16

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_rename_obs_source_ehs_to_data_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forecast_cycle',
            },
        ),
    ]
