# Generated by Django 5.1.1 on 2024-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_calibrationparameter_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationinput',
            name='default_value',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optimizationinput',
            name='max',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='optimizationinput',
            name='min',
            field=models.FloatField(null=True),
        ),
    ]
