# Generated by Django 5.1.1 on 2024-10-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_rename_job_id_performancemetrics_slurm_job_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iterationparameter',
            name='best',
        ),
        migrations.AddField(
            model_name='iteration',
            name='best_params',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ValidationGlobalMetric',
        ),
    ]
