# Generated by Django 5.1.2 on 2024-11-14 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_forecastcycle'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE observational_source SET name = 'Data Services' WHERE name = 'Agency';",
            reverse_sql="UPDATE observational_source SET name = 'Agency' WHERE name = 'Data Services';"
        ),
    ]
