# Generated by Django 5.0.6 on 2024-07-10 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_alter_calibrationformulation_calibration_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gage',
            name='discharge_period',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gage',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.domain'),
        ),
    ]
