# Generated by Django 5.1.1 on 2024-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_optimizationinput_default_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdefinitions',
            name='location',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotdefinitions',
            name='valid_optimizations',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plotdefinitions',
            name='validation',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationformulation',
            name='groups',
            field=models.TextField(),
        ),
    ]
