# Generated by Django 5.0.7 on 2024-08-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_remove_calibrationrun_run_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iterationmetric',
            name='metric_value',
            field=models.FloatField(null=True),
        ),
    ]
