# Generated by Django 5.0.6 on 2024-07-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_alter_optimizationinput_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationrun',
            old_name='calibration_run_pk_tune_parameters',
            new_name='calibration_run_tune_parameters',
        ),
        migrations.RemoveField(
            model_name='calibrationtuneparameter',
            name='calibration_run',
        ),
        migrations.AddField(
            model_name='calibrationinitialparameter',
            name='calibratable',
            field=models.BooleanField(default=False),
        ),
    ]
