# Generated by Django 5.0.6 on 2024-07-02 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_alter_gage_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationformulation',
            old_name='calibration_run_pk',
            new_name='calibration_run',
        ),
        migrations.RenameField(
            model_name='calibrationformulation',
            old_name='module_pk',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='calibrationinitialparameter',
            old_name='calibration_run_pk',
            new_name='calibration_run',
        ),
        migrations.RenameField(
            model_name='calibrationmetric',
            old_name='calibration_run_pk',
            new_name='calibration_run',
        ),
        migrations.RenameField(
            model_name='calibrationmetricinput',
            old_name='calibration_metric_pk',
            new_name='calibration_metric',
        ),
        migrations.RenameField(
            model_name='calibrationoptimizationinput',
            old_name='calibration_run_pk',
            new_name='calibration_run',
        ),
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='gage_pk',
            new_name='gage',
        ),
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='module_output_variable_pk',
            new_name='module_output_variable',
        ),
        migrations.RenameField(
            model_name='calibrationstopcriteria',
            old_name='calibration_run_pk',
            new_name='calibration_run',
        ),
        migrations.RenameField(
            model_name='calibrationtuneparameter',
            old_name='calibration_run_pk',
            new_name='calibration_run',
        ),
        migrations.RenameField(
            model_name='iteration',
            old_name='calibration_run_pk',
            new_name='calibration_run',
        ),
        migrations.RenameField(
            model_name='iterationmetric',
            old_name='calibration_metric_pk',
            new_name='calibration_metric',
        ),
        migrations.RenameField(
            model_name='iterationmetric',
            old_name='iteration_pk',
            new_name='iteration',
        ),
        migrations.RenameField(
            model_name='iterationresult',
            old_name='iteration_pk',
            new_name='iteration',
        ),
        migrations.RenameField(
            model_name='iterationtuneparameter',
            old_name='iteration_pk',
            new_name='iteration',
        ),
        migrations.RenameField(
            model_name='validationrun',
            old_name='calibration_run_pk',
            new_name='calibration_run',
        ),
        migrations.RemoveField(
            model_name='calibrationinitialparameter',
            name='module_pk',
        ),
        migrations.RemoveField(
            model_name='calibrationmetric',
            name='metric_pk',
        ),
        migrations.RemoveField(
            model_name='calibrationmetricinput',
            name='metric_pk',
        ),
        migrations.RemoveField(
            model_name='calibrationoptimizationinput',
            name='optimization_input_pk',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='optimization_pk',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='status_pk',
        ),
        migrations.RemoveField(
            model_name='calibrationslothparam',
            name='calibration_run_pk',
        ),
        migrations.RemoveField(
            model_name='calibrationtuneparameter',
            name='calibration_initial_parameter_pk',
        ),
        migrations.RemoveField(
            model_name='iterationtuneparameter',
            name='calibration_initial_parameter_pk',
        ),
        migrations.RemoveField(
            model_name='metricinput',
            name='metric_pk',
        ),
        migrations.RemoveField(
            model_name='optimizationinput',
            name='optimization_pk',
        ),
        migrations.RemoveField(
            model_name='validationrun',
            name='status_pk',
        ),
        migrations.AddField(
            model_name='calibrationinitialparameter',
            name='module',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.module'),
        ),
        migrations.AddField(
            model_name='calibrationmetric',
            name='metric',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.metric'),
        ),
        migrations.AddField(
            model_name='calibrationmetricinput',
            name='metric_input',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.metricinput'),
        ),
        migrations.AddField(
            model_name='calibrationoptimizationinput',
            name='optimization_input',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.optimizationinput'),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='optimization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.optimization'),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.status'),
        ),
        migrations.AddField(
            model_name='calibrationslothparam',
            name='calibration_run',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationrun'),
        ),
        migrations.AddField(
            model_name='calibrationslothparam',
            name='maps_to_module',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.module'),
        ),
        migrations.AddField(
            model_name='calibrationtuneparameter',
            name='calibration_initial_parameter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationinitialparameter'),
        ),
        migrations.AddField(
            model_name='iterationtuneparameter',
            name='calibration_initial_parameter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.calibrationinitialparameter'),
        ),
        migrations.AddField(
            model_name='metricinput',
            name='metric',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.metric'),
        ),
        migrations.AddField(
            model_name='optimizationinput',
            name='optimization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.optimization'),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.status'),
        ),
    ]
