# Generated by Django 5.1.4 on 2025-02-20 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_rename_is_deleted_calibrationrun_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='module_output_variable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.moduleoutputvariable'),
        ),
        migrations.AlterField(
            model_name='nwmretrospectivemetrics',
            name='calibration_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
        ),
        migrations.AlterField(
            model_name='validationmetrics',
            name='validation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calibration.validationrun'),
        ),
    ]
