# Generated by Django 5.0.6 on 2024-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0009_rename_calibration_run_pk_calibrationformulation_calibration_run_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='description',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='ngen_commit_hash',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='calibration_end_period',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='calibration_eval_end_period',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='calibration_eval_start_period',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='calibration_start_period',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='forcing_user_filename',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='formulation_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='hydrofabric_gpkg_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='observational_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='plot_frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='run_type',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='seed',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='time_range_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='time_range_start',
            field=models.DateTimeField(null=True),
        ),
    ]
