# Generated by Django 5.0.6 on 2024-07-10 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0009_gage_discharge_period_alter_gage_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gage',
            name='discharge_period',
        ),
    ]
