# Generated by Django 5.0.7 on 2024-08-16 22:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0010_iteration_iteration_iteration_num_calibration_run__unique'), ('calibration', '0011_alter_iteration_iteration_num')]

    dependencies = [
        ('calibration', '0009_alter_iterationmetric_metric_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='iteration',
            constraint=models.UniqueConstraint(fields=('iteration_num', 'calibration_run'), name='iteration_iteration_num_calibration_run__unique'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='iteration_num',
            field=models.IntegerField(),
        ),
    ]
