# Generated by Django 5.1.4 on 2025-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0009_alter_calibrationrun_module_output_variable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotdefinition',
            name='timeseries_available',
            field=models.BooleanField(default=False),
        ),
    ]
