# Generated by Django 5.1.1 on 2024-09-17 20:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0009_plotdefinitions_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlotDefinitions',
            new_name='PlotDefinition',
        ),
    ]
