# Generated by Django 5.1.2 on 2024-11-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0009_rename_agency_from_obs_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
