# Generated by Django 5.1.2 on 2024-11-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0010_calibrationrun_end_date_validationrun_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='end_date',
            new_name='run_end',
        ),
        migrations.RenameField(
            model_name='validationrun',
            old_name='end_date',
            new_name='run_end',
        ),
    ]
