# Generated by Django 5.1.4 on 2025-03-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0010_plotdefinition_timeseries_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='module_output_variable',
        ),
        migrations.DeleteModel(
            name='ModuleOutputVariable',
        ),
    ]
