# Generated by Django 5.0.6 on 2024-07-10 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0010_remove_gage_description_remove_gage_discharge_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='gage',
            name='observational_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.observationalsource'),
        ),
    ]
