# Generated by Django 5.0.6 on 2024-07-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0010_remove_calibrationrun_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinputvariable',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moduleoutputvariable',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='moduleinputvariable',
            unique_together={('name', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='moduleoutputvariable',
            unique_together={('name', 'module')},
        ),
    ]
