# Generated by Django 5.0.8 on 2024-08-17 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0010_iteration_iteration_iteration_num_calibration_run__unique_squashed_0011_alter_iteration_iteration_num'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationformulation',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='ngen_cal_commit_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='ngen_commit_hash',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='ngen_formulation_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='plot_frequency',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='user_formulation_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calibrationtuneparameter',
            name='data_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='calibrationtuneparameter',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='forcingsource',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gage',
            name='agency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gage',
            name='gage_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='gage',
            name='huc',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gage',
            name='nws_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gage',
            name='site_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gage',
            name='station_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='iterationtuneparameter',
            name='data_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='moduleoutputvariable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ngencalformulation',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='observationalsource',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='optimization',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='optimization',
            name='stop_criteria_data_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='optimization',
            name='stop_criteria_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='optimizationinput',
            name='data_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='optimizationinput',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='plotdefinitions',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='rfc',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='calibration_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='validations', to='calibration.calibrationrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
