# Generated by Django 5.1.2 on 2024-11-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0011_rename_end_date_calibrationrun_run_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='run_date',
            new_name='submit_date',
        ),
        migrations.RenameField(
            model_name='validationrun',
            old_name='run_date',
            new_name='submit_date',
        ),
    ]
