# Generated by Django 5.0.6 on 2024-07-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0011_gage_observational_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='description',
        ),
        migrations.RemoveField(
            model_name='status',
            name='is_active',
        ),
    ]
