# Generated by Django 5.0.6 on 2024-07-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0012_remove_status_description_remove_status_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='status',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
