# Generated by Django 5.1.2 on 2024-11-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0012_rename_run_date_calibrationrun_submit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='run_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='validationrun',
            name='run_start',
            field=models.DateTimeField(null=True),
        ),
    ]
