# Generated by Django 5.1.1 on 2024-09-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0011_geopackagesource_squashed_0012_calibrationrun_geopackage_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='geopackage_hydrofabric_path',
            new_name='geopackage_hydrofabric_file_path',
        ),
    ]
