# Generated by Django 5.0.8 on 2024-08-19 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0013_rename_worker_iteration_worker_name_and_more'), ('calibration', '0014_remove_iteration_iteration_iteration_num_calibration_run__unique_and_more'), ('calibration', '0015_remove_iteration_best_for_worker_and_more')]

    dependencies = [
        ('calibration', '0012_alter_calibrationformulation_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='iteration',
            old_name='worker',
            new_name='worker_name',
        ),
        migrations.AddField(
            model_name='iteration',
            name='worker_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='calibration_output_variable_value',
            field=models.FloatField(null=True),
        ),
        migrations.RemoveConstraint(
            model_name='iteration',
            name='iteration_iteration_num_calibration_run__unique',
        ),
        migrations.AddConstraint(
            model_name='iteration',
            constraint=models.UniqueConstraint(fields=('iteration_num', 'worker_name', 'calibration_run'), name='iteration_iteration_num_worker_calibration_run__unique'),
        ),
        migrations.RemoveField(
            model_name='iteration',
            name='best_for_worker',
        ),
        migrations.RemoveField(
            model_name='iteration',
            name='best_overall',
        ),
    ]
