# Generated by Django 5.1.2 on 2024-11-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0013_calibrationrun_run_start_validationrun_run_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationrun',
            name='validation_worker_name',
            field=models.CharField(null=True),
        ),
    ]
