# Generated by Django 5.1.1 on 2024-09-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0013_rename_geopackage_hydrofabric_path_calibrationrun_geopackage_hydrofabric_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='plot_frequency',
            new_name='save_plot_iteration_frequency',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='save_output_iteration_frequency',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
