# Generated by Django 5.1.3 on 2024-11-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0013_calibrationrun_run_start_validationrun_run_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotdefinition',
            name='validation',
        ),
        migrations.AddField(
            model_name='plotdefinition',
            name='job_type',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plotdefinition',
            name='valid_optimizations',
            field=models.TextField(null=True),
        ),
    ]
