# Generated by Django 5.0.6 on 2024-07-11 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0013_alter_calibrationrun_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationslothparam',
            name='calibration_run',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationslothparam',
            name='maps_to_module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationformulation'),
            preserve_default=False,
        ),
    ]
