# Generated by Django 5.1.1 on 2024-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0014_rename_plot_frequency_calibrationrun_save_plot_iteration_frequency_and_more'), ('calibration', '0015_remove_calibrationrun_save_output_iteration_frequency_and_more'), ('calibration', '0016_alter_calibrationrun_save_output_iteration')]

    dependencies = [
        ('calibration', '0013_rename_geopackage_hydrofabric_path_calibrationrun_geopackage_hydrofabric_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='plot_frequency',
            new_name='save_plot_iteration_frequency',
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='save_output_iteration',
            field=models.BooleanField(default=False),
        ),
    ]
