# Generated by Django 5.1.3 on 2024-11-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0014_remove_plotdefinition_validation_and_more'),
        ('calibration', '0014_validationrun_validation_worker_name'),
    ]

    operations = [
    ]
