# Generated by Django 5.1.3 on 2024-11-21 03:24

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0015_merge_20241121_0321'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('run_start', models.DateTimeField(null=True)),
                ('run_end', models.DateTimeField(null=True)),
                ('slurm_job_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'forecast_run',
            },
        ),
        migrations.AddField(
            model_name='forecastcycle',
            name='data_sources',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='forecastcycle',
            name='time_range',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='iteration',
            index=models.Index(fields=['calibration_run'], name='iteration_calibration_run_idx'),
        ),
        migrations.AddIndex(
            model_name='iteration',
            index=models.Index(fields=['worker_number'], name='iteration_worker_number_idx'),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='calibration_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='calibration.calibrationrun'),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='performance_metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.performancemetrics'),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status'),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
