# Generated by Django 5.0.6 on 2024-07-15 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0015_status_alter_calibrationrun_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationinitialparameter',
            name='data_type',
            field=models.TextField(default='double'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationinitialparameter',
            name='calibration_formulation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationformulation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationinitialparameter',
            name='calibration_run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
            preserve_default=False,
        ),
    ]
