# Generated by Django 5.0.8 on 2024-08-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0013_rename_worker_iteration_worker_name_and_more_squashed_0015_remove_iteration_best_for_worker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iterationtuneparameter',
            name='best',
            field=models.BooleanField(default=False),
        ),
    ]
