# Generated by Django 5.1.3 on 2024-11-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0016_forecastrun_forecastcycle_data_sources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastcycle',
            name='description',
        ),
    ]
