# Generated by Django 5.1.1 on 2024-09-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0014_rename_plot_frequency_calibrationrun_save_plot_iteration_frequency_and_more_squashed_0016_alter_calibrationrun_save_output_iteration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='ngen_formulation_name',
        ),
        migrations.DeleteModel(
            name='NgenCalFormulation',
        ),
    ]
