# Generated by Django 5.0.6 on 2024-07-15 14:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0016_calibrationinitialparameter_data_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calibrationinitialparameter',
            constraint=models.UniqueConstraint(fields=('name', 'calibration_formulation', 'calibration_run'), name='calibration_initial_parameter__name__calibration_formulation__unique'),
        ),
    ]
