# Generated by Django 5.0.8 on 2024-08-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0016_iterationtuneparameter_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='user_parameter_filename',
            field=models.TextField(null=True),
        ),
    ]
