# Generated by Django 5.0.8 on 2024-08-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0017_calibrationrun_user_parameter_filename'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rfc',
            table='rfc',
        ),
    ]
