# Generated by Django 5.1.1 on 2024-09-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0017_remove_calibrationrun_ngen_formulation_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='slurm_job_id',
            field=models.IntegerField(null=True),
        ),
    ]
