# Generated by Django 5.0.6 on 2024-07-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0017_calibrationinitialparameter_calibration_initial_parameter__name__calibration_formulation__unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationinitialparameter',
            name='name',
            field=models.TextField(),
        ),
    ]
