# Generated by Django 5.1.3 on 2024-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0017_remove_forecastcycle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastcycle',
            name='data_sources',
            field=models.CharField(default='tbd', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forecastcycle',
            name='time_range',
            field=models.CharField(default='tbd', max_length=100),
            preserve_default=False,
        ),
    ]
