# Generated by Django 5.0.8 on 2024-08-23 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('calibration', '0019_alter_gage_gage_id_and_more'), ('calibration', '0020_calibrationtuneparameter_user_selected_for_tuning')]

    dependencies = [
        ('calibration', '0018_alter_rfc_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gage',
            name='gage_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='gage',
            constraint=models.UniqueConstraint(fields=('gage_id', 'agency'), name='gage__gage_id__agency__unique'),
        ),
        migrations.AddField(
            model_name='calibrationtuneparameter',
            name='user_selected_for_tuning',
            field=models.BooleanField(default=False),
        ),
    ]
