# Generated by Django 5.1.3 on 2024-11-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0018_alter_forecastcycle_data_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastrun',
            name='cycle_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='calibration.forecastcycle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='have_forcing_data',
            field=models.BooleanField(default=False),
        ),
    ]
