# Generated by Django 5.0.6 on 2024-07-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0018_alter_calibrationinitialparameter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricinput',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='calibrationmetric',
            name='calibration_run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationmetric',
            name='metric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.metric'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationmetric',
            name='objective_function',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='calibrationmetricinput',
            name='calibration_metric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationmetric'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationmetricinput',
            name='metric_input',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.metricinput'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationoptimizationinput',
            name='calibration_run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationoptimizationinput',
            name='optimization_input',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.optimizationinput'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationtuneparameter',
            name='calibration_initial_parameter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationinitialparameter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationtuneparameter',
            name='calibration_run',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationrun'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iteration',
            name='best',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iterationtuneparameter',
            name='calibration_initial_parameter',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.calibrationinitialparameter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iterationtuneparameter',
            name='iteration',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.iteration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metricinput',
            name='metric',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calibration.metric'),
            preserve_default=False,
        ),
    ]
