# Generated by Django 5.0.8 on 2024-08-23 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0018_alter_rfc_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='gage',
            name='gage_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='gage',
            constraint=models.UniqueConstraint(fields=('gage_id', 'agency'), name='gage__gage_id__agency__unique'),
        ),
    ]
