# Generated by Django 5.1.3 on 2024-11-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0019_forecastrun_cycle_name_forecastrun_have_forcing_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastrun',
            old_name='cycle_name',
            new_name='cycle',
        ),
    ]
