# Generated by Django 5.1.3 on 2024-11-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0020_rename_cycle_name_forecastrun_cycle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gage',
            old_name='nwm_v3_calibrated',
            new_name='nwm_v3_calibration',
        ),
        migrations.AddField(
            model_name='gage',
            name='headwater_calibration',
            field=models.BooleanField(default=False),
        ),
    ]
