# Generated by Django 5.0.8 on 2024-08-23 18:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0019_alter_gage_gage_id_and_more_squashed_0020_calibrationtuneparameter_user_selected_for_tuning'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalibrationTuneParameter',
            new_name='CalibrationParameter',
        ),
        migrations.RenameModel(
            old_name='IterationTuneParameter',
            new_name='IterationParameter',
        ),
        migrations.AlterModelTable(
            name='calibrationparameter',
            table='calibration_parameter',
        ),
        migrations.AlterModelTable(
            name='iterationparameter',
            table='iteration_parameter',
        ),
    ]
