# Generated by Django 5.1.3 on 2024-11-26 01:58

import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0020_rename_cycle_name_forecastrun_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastrun',
            name='have_forcing_data',
        ),
        migrations.CreateModel(
            name='ForecastForcingDownloadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submit_date', models.DateTimeField(null=True)),
                ('run_start', models.DateTimeField(null=True)),
                ('run_end', models.DateTimeField(null=True)),
                ('slurm_job_id', models.IntegerField(null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(db_column='created_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('performance_metrics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.performancemetrics')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='calibration.status')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(db_column='updated_by', default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.RESTRICT, on_update=True, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forecast_forcing_download_run',
            },
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='forcing_download_run',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_run', to='calibration.forecastforcingdownloadrun'),
            preserve_default=False,
        ),
    ]
