# Generated by Django 5.1.3 on 2024-11-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0022_remove_forecastrun_have_forcing_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='performance_metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calibration.performancemetrics'),
        ),
        migrations.AlterField(
            model_name='validationrun',
            name='validation_worker_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
