# Generated by Django 5.1.3 on 2024-11-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0021_rename_nwm_v3_calibrated_gage_nwm_v3_calibration_and_more'),
        ('calibration', '0023_alter_calibrationrun_performance_metrics_and_more'),
    ]

    operations = [
    ]
