# Generated by Django 5.1.3 on 2024-11-29 03:13

import django.db.models.expressions
import django.db.models.functions.comparison
from django.db import migrations, models
from django.db import connection


def convert_char_to_integer(apps, schema_editor):
    """
    Converts CharField values to IntegerField by stripping suffixes (K, M, G)
    and converting them to integers in kilobytes.
    """
    with connection.cursor() as cursor:
        # Update max_disk_read
        cursor.execute("""
            UPDATE performance_metrics
            SET max_disk_read = CASE
                WHEN max_disk_read LIKE '%K' THEN CAST(REPLACE(max_disk_read, 'K', '') AS INTEGER)
                WHEN max_disk_read LIKE '%M' THEN CAST(REPLACE(max_disk_read, 'M', '') AS FLOAT) * 1024
                WHEN max_disk_read LIKE '%G' THEN CAST(REPLACE(max_disk_read, 'G', '') AS FLOAT) * 1024 * 1024
                ELSE CAST(max_disk_read AS INTEGER)
            END
            WHERE max_disk_read IS NOT NULL;
        """)

        # Update max_disk_write
        cursor.execute("""
            UPDATE performance_metrics
            SET max_disk_write = CASE
                WHEN max_disk_write LIKE '%K' THEN CAST(REPLACE(max_disk_write, 'K', '') AS INTEGER)
                WHEN max_disk_write LIKE '%M' THEN CAST(REPLACE(max_disk_write, 'M', '') AS FLOAT) * 1024
                WHEN max_disk_write LIKE '%G' THEN CAST(REPLACE(max_disk_write, 'G', '') AS FLOAT) * 1024 * 1024
                ELSE CAST(max_disk_write AS INTEGER)
            END
            WHERE max_disk_write IS NOT NULL;
        """)

        # Update max_rss
        cursor.execute("""
            UPDATE performance_metrics
            SET max_rss = CASE
                WHEN max_rss LIKE '%K' THEN CAST(REPLACE(max_rss, 'K', '') AS INTEGER)
                WHEN max_rss LIKE '%M' THEN CAST(REPLACE(max_rss, 'M', '') AS FLOAT) * 1024
                WHEN max_rss LIKE '%G' THEN CAST(REPLACE(max_rss, 'G', '') AS FLOAT) * 1024 * 1024
                ELSE CAST(max_rss AS INTEGER)
            END
            WHERE max_rss IS NOT NULL;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0024_merge_20241126_1455'),
    ]

    operations = [
        # Step 1: Add io_throughput field as a GeneratedField
        migrations.AddField(
            model_name='performancemetrics',
            name='io_throughput',
            field=models.GeneratedField(
                db_persist=True,
                expression=models.ExpressionWrapper(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Coalesce(models.F('max_disk_read'), models.Value(0)),
                            '+',
                            django.db.models.functions.comparison.Coalesce(models.F('max_disk_write'), models.Value(0)),
                        ),
                        '/',
                        django.db.models.functions.comparison.NullIf(
                            models.ExpressionWrapper(models.F('elapsed_time'), output_field=models.FloatField()), 0
                        )
                    ),
                    output_field=models.FloatField(),
                ),
                output_field=models.FloatField(),
            ),
        ),
        # Step 2: Convert data in CharField format to integers
        migrations.RunPython(convert_char_to_integer),
        # Step 3: Alter fields to IntegerField
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_disk_read',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_disk_write',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='performancemetrics',
            name='max_rss',
            field=models.IntegerField(null=True),
        ),
    ]