# Generated by Django 5.2.5 on 2025-09-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0024_outputvariable_module_output_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='is_aet_rootzone',
            field=models.BooleanField(default=False),
        ),
    ]
