# Generated by Django 5.2.13 on 2026-05-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0071_rename_forcing_source_requested_calibrationrun_forcing_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ad_guid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_ldap_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
