# Generated by Django 5.2.14 on 2026-05-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0072_customuser_ad_guid_customuser_last_ldap_sync'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_local_only',
            field=models.BooleanField(default=False),
        ),
    ]
