# Generated by Django 5.2.14 on 2026-06-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0073_customuser_is_local_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='calibration_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='validation_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='validation_window',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='warmup_duration',
            field=models.IntegerField(null=True),
        ),
    ]
