# Generated by Django 5.2.14 on 2026-06-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0074_calibrationrun_calibration_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrationrun',
            name='validation_window',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
