# Generated by Django 5.2.14 on 2026-06-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0074_calibrationrun_calibration_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='calibration_end_period',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='validation_end_period',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='validation_start_period',
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='calibration_duration',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='validation_duration',
            field=models.IntegerField(default=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calibrationrun',
            name='warmup_duration',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
