# Generated by Django 5.2.14 on 2026-06-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0075_remove_calibrationrun_calibration_end_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='user_parameter_filename',
        ),
    ]
