# Generated by Django 5.2.14 on 2026-06-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0076_remove_calibrationrun_user_parameter_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibrationrun',
            name='automatic_validation',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='calibration_end_period',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='calibration_eval_end_period',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='calibration_eval_start_period',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='validation_end_period',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='validation_eval_end_period',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='validation_eval_start_period',
        ),
        migrations.RemoveField(
            model_name='calibrationrun',
            name='validation_start_period',
        ),
    ]
