# Generated by Django 5.2.14 on 2026-06-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0077_remove_calibrationrun_automatic_validation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calibrationrun',
            old_name='validation_window',
            new_name='validation_window_after_calibration',
        ),
    ]
