# Generated by Django 5.2.14 on 2026-06-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0078_rename_validation_window_calibrationrun_validation_window_after_calibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='validation_window_gap',
            field=models.IntegerField(null=True),
        ),
    ]
