# Generated by Django 5.2.14 on 2026-07-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0079_calibrationrun_validation_window_gap'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationrun',
            name='threshold_categorical',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='calibrationrun',
            name='threshold_event',
            field=models.FloatField(null=True),
        ),
    ]
